### ISSUE TITLE
Update Dompdf to 0.7.x because of security vulnerabilities in 0.6.x

### ISSUE THREAD

**Issue by simison** [anttiviljami/wp-pdf-templates#14]
There are a few important security patches in latest 0.6.x and latest 0.7.x has some breaking changes:

https://github.com/dompdf/dompdf/wiki/Securing-dompdf#previously-disclosed-vulnerabilities

https://github.com/dompdf/dompdf/wiki/Migration-Guide

https://github.com/dompdf/dompdf/releases

**Comment by anttiviljami** [comment]
We are currently on v0.7.0-beta3. Thanks for letting us know about the vulns.
