### ISSUE TITLE
tfoot not rendered properly

### ISSUE THREAD

**Issue by darkolaz** [anttiviljami/wp-pdf-templates#2]
Was trying to convert a html to pdf and noticed this bug,

I have table with thead, tfoot and tbody, as i know thead and tfoot should be repeated if i have multiple pdf pages. Thead works very well, its where it should be on every page on top. Problem is the tfoot, if i place tfoot after thead between and before tbody, the footer shows on top and only on the first page. If i place it after tbody it shows at the end of the pdf document and its not repeating. Is this a plugin issue or i should report this problem at dompdf guys?

Btw, this plugin is awesome,
Thanks

**Comment by anttiviljami** [comment]
I'm afraid this is a dompdf issue, not the plugin's. 

This plugin simply makes it possible to pipe html output from WordPress to dompdf. 

I suggest you try fiddling about with dompdf's settings to see if anything would help. I haven't seen any updates from the dompdf guys in a while so a patch seems unlikely.
