### ISSUE TITLE
DOMPDF_Exception thrown  Requested HTML document contains no data.

### ISSUE THREAD

**Issue by sam-suresh** [anttiviljami/wp-pdf-templates#7]
I got this error;
DOMPDF_Exception thrown
Requested HTML document contains no data.

WP with Visual Composer

**Comment by onnimonni** [comment]
Can you provide more context?

Tell us about:
- What is your environment like php and web server version?
- how are you using this plugin?
- what other plugins are you using?
- Has it been working earlier?
