### ISSUE TITLE
Plugin could not be activated

### ISSUE THREAD

**Issue by ghost** [anttiviljami/wp-pdf-templates#8]
I have downloaded the plugin directly from GIT, installed to the plugins upload directory and tried to activate.

Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /home/fuldemo/public_html/wp-content/plugins/wp-pdf-templates/wp-pdf-templates.php on line 167

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /home/fuldemo/public_html/wp-content/plugins/wp-pdf-templates/wp-pdf-templates.php on line 167

**Comment by anttiviljami** [comment]
Cloning this plugin directly from the github repository you need to run a `composer install` in order for all the plugin dependencies to load.

Generally I would suggest just using the WordPress.org version production installs. The master branch of this plugin is usually a few commits ahead the wordpress.org version and might not be stable.

**Comment by ghost** [comment]
Ok. I will try the WP.org version. Thank you for advising.  I didn't realise this is in the directory.
